baseURL = "https://thibautvas.com/"
languageCode = "en-us"
title = "Thibaut Vas"
theme = "tailwind"

[markup]
  _merge = "deep"

[params]
  subtitle = ""
  contentTypeName = "posts"

  [params.header]
    logo = "logo.webp"

  [params.footer]
    since = 2025
    poweredby = true

[menu]

  [[menu.main]]
    identifier = "post"
    name = "Post"
    pageRef = "/posts"
    weight = 10

  [[menu.main]]
    identifier = "about"
    name = "About"
    pageRef = "/about"
    weight = 20

[taxonomies]
category = "categories"
tag = "tags"
series = "series"
